#!/usr/bin/env python3
"""Bind each translated README section to the English section it mirrors.

`README.md` is the only document that states what the project does, what it
guarantees, and how to install it. A translation of it rots at the first
release that changes an install command, and a stale install command in a
translated file is worse than no translated file: it is a documented
instruction that fails, in a file nobody re-reads.

So the translations are not hand-maintained prose sitting next to the English.
Every translated section carries the content hash of the English section it
mirrors, recorded in a comment block that GitHub does not render. When an
English section changes and its translation does not, this fails and names the
language and the heading - the operator must not have to diff eight files to
find the one paragraph.

Usage::

    python scripts/check_readme_translations.py           # verify, exit 1 on drift
    python scripts/check_readme_translations.py --update  # rebind after translating

The language set lives in ``docs/i18n/languages.json``, so adding a language is
a data change and a new file, not a code change.

Two normalisations decide what counts as a change, and both are deliberate:

* **Whitespace is collapsed.** A rewrap of an English paragraph does not change
  what it says, and a gate that cries wolf on every reformat gets disabled
  within a month.
* **Link targets are masked.** This repository has twice rewritten every link
  in the README mechanically - relative to absolute for PyPI - without
  changing a word of prose. Invalidating every translation over that would
  teach the next person to run ``--update`` without reading, which is how a
  gate becomes a rubber stamp. Link *text* is prose and is hashed.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ENGLISH = REPO_ROOT / "README.md"
LANGUAGES = REPO_ROOT / "docs" / "i18n" / "languages.json"

#: Wraps the language links line, in every README including the English one.
#: Generated from ``languages.json`` so adding a language is a data change.
LINKS_START = "<!-- language-links -->"
LINKS_END = "<!-- /language-links -->"

#: Blob URL prefix. The English README is the packaged long description, so a
#: repo-relative link to a translation would 404 on PyPI (see #3441).
BLOB = "https://github.com/sipyourdrink-ltd/bernstein/blob/main/"

#: Opens the binding block. Everything up to :data:`BINDING_END` is generated.
BINDING_START = "<!-- translation-binding v1 -- generated by scripts/check_readme_translations.py"
BINDING_END = "-->"

_HEADING = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
_FENCE = re.compile(r"^\s*(```|~~~)")
_LINK_OPEN = re.compile(r"(!?\[[^\]]*\])\(")
_INLINE_CODE = re.compile(r"`([^`\n]+)`")
_WHITESPACE = re.compile(r"\s+")


@dataclass(frozen=True)
class Section:
    """One heading and the body under it, in file order."""

    index: int
    level: int
    heading: str
    body: str

    @property
    def key(self) -> str:
        """Stable name for this section: its position and English heading.

        The separator is a pipe rather than a space so the key survives being
        read back out of a stripped line - the preamble has no heading, and
        `"00 ".strip()` would silently become a different key.
        """
        return f"{self.index:02d}|{self.heading}"


def _label(key: str) -> str:
    """Human-facing name for a section key, for the failure message."""
    _, _, heading = key.partition("|")
    return heading or "(the block before the first heading)"


def split_sections(text: str) -> list[Section]:
    """Split *text* into sections at ATX headings.

    Fenced blocks are tracked, because a shell prompt (``# comment``) inside a
    code block is not a heading and splitting on it would invent a section that
    exists in one file and not the other.
    """
    sections: list[Section] = []
    level, heading, body, index = 0, "", [], 0
    fence: str | None = None

    for line in text.splitlines():
        opener = _FENCE.match(line)
        if opener:
            marker = opener.group(1)
            fence = None if fence == marker else (fence or marker)
        match = None if fence else _HEADING.match(line)
        if match:
            if heading or body:
                sections.append(Section(index, level, heading, "\n".join(body)))
                index += 1
            level, heading, body = len(match.group(1)), match.group(2), []
            continue
        body.append(line)

    if heading or body:
        sections.append(Section(index, level, heading, "\n".join(body)))
    return sections


def mask_link_targets(text: str) -> str:
    """Replace every markdown link destination with a placeholder.

    Written as a scan rather than a regex because a destination may contain
    balanced parentheses - ``[x](https://en.example/Foo_(bar))`` is an ordinary
    link, and a pattern that stops at the first ``)`` masks half of it, which
    makes an untouched section hash differently depending on what is inside the
    brackets. Link *text* is left alone: it is prose, and prose is the thing
    being tracked.
    """
    out: list[str] = []
    index = 0
    while True:
        match = _LINK_OPEN.search(text, index)
        if match is None:
            out.append(text[index:])
            return "".join(out)
        out.append(text[index : match.start()])
        out.append(match.group(1))
        depth, cursor = 1, match.end()
        while cursor < len(text) and depth:
            if text[cursor] == "(":
                depth += 1
            elif text[cursor] == ")":
                depth -= 1
            cursor += 1
        if depth:
            # Unbalanced: not a link after all, so nothing is masked.
            out.append(text[match.end() - 1 :])
            return "".join(out)
        out.append("(<link>)")
        index = cursor


def normalise(section: Section) -> str:
    """Reduce a section to what a translation actually has to track."""
    text = f"{section.level} {section.heading}\n{section.body}"
    return _WHITESPACE.sub(" ", mask_link_targets(text)).strip()


def section_hash(section: Section) -> str:
    return hashlib.sha256(normalise(section).encode("utf-8")).hexdigest()[:16]


def fenced_blocks(text: str) -> list[str]:
    """Every fenced code block, in document order.

    A code block is a unit of the document, so its position is structure: the
    third block of the English file has to be the third block of every
    translation, byte for byte. A translated command is not a rough edge, it is
    an instruction that fails.
    """
    blocks: list[str] = []
    fence: str | None = None
    block: list[str] = []
    for line in text.splitlines():
        opener = _FENCE.match(line)
        if opener:
            marker = opener.group(1)
            if fence == marker:
                blocks.append("\n".join(block))
                fence, block = None, []
            elif fence is None:
                fence = marker
            continue
        if fence:
            block.append(line)
    return blocks


def inline_code(text: str) -> list[str]:
    """Every inline code span, sorted.

    Sorted rather than ordered, because a sentence's clauses move when it is
    translated - Chinese puts the environment variable before the command
    where English puts it after - and the property under test is that the same
    commands, flags and paths appear, not that the prose around them kept
    English word order.
    """
    spans: list[str] = []
    fence: str | None = None
    for line in text.splitlines():
        opener = _FENCE.match(line)
        if opener:
            marker = opener.group(1)
            fence = None if fence == marker else (fence or marker)
            continue
        if not fence:
            spans.extend(_INLINE_CODE.findall(line))
    return sorted(spans)


def languages() -> list[dict[str, str]]:
    data = json.loads(LANGUAGES.read_text(encoding="utf-8"))
    entries: list[dict[str, str]] = data["languages"]
    return entries


def translation_path(tag: str) -> Path:
    return REPO_ROOT / f"README.{tag}.md"


def language_line(current: str) -> str:
    """The links line as it should read in the file for *current*.

    ``current`` is the language tag of the file, or ``"en"`` for the English
    one; that variant is listed as plain text rather than a link to itself.
    """
    parts = []
    for entry in [{"tag": "en", "name": "English"}, *languages()]:
        name = entry["name"]
        if entry["tag"] == current:
            parts.append(f"**{name}**")
        else:
            target = "README.md" if entry["tag"] == "en" else f"README.{entry['tag']}.md"
            parts.append(f"[{name}]({BLOB}{target})")
    return " &middot; ".join(parts)


def replace_language_line(text: str, current: str) -> str:
    """Rewrite the marked links line, or report that the markers are missing."""
    if LINKS_START not in text or LINKS_END not in text:
        raise ValueError(f"{LINKS_START} ... {LINKS_END} markers are missing")
    head, rest = text.split(LINKS_START, 1)
    _, tail = rest.split(LINKS_END, 1)
    return f"{head}{LINKS_START}\n{language_line(current)}\n{LINKS_END}{tail}"


def current_language_line(text: str) -> str | None:
    if LINKS_START not in text or LINKS_END not in text:
        return None
    return text.split(LINKS_START, 1)[1].split(LINKS_END, 1)[0].strip()


def read_binding(text: str) -> dict[str, str]:
    """Parse the generated block into ``{section key: hash}``."""
    if BINDING_START not in text:
        return {}
    block = text.split(BINDING_START, 1)[1].split(BINDING_END, 1)[0]
    bound: dict[str, str] = {}
    for line in block.splitlines():
        if "=" not in line:
            continue
        key, _, digest = line.strip().rpartition("=")
        bound[key.strip()] = digest.strip()
    return bound


def render_binding(sections: list[Section]) -> str:
    lines = [
        BINDING_START,
        "     Each line binds a section of this file to the English section at the same",
        "     position. `python scripts/check_readme_translations.py` fails when one",
        "     moves and this does not. Re-run it with --update after translating.",
    ]
    lines += [f"     {section.key}={section_hash(section)}" for section in sections]
    lines.append(BINDING_END)
    return "\n".join(lines)


def strip_binding(text: str) -> str:
    if BINDING_START not in text:
        return text
    head, rest = text.split(BINDING_START, 1)
    return head + rest.split(BINDING_END, 1)[1].lstrip("\n")


def verify() -> list[str]:
    """Return one readable problem per drift, naming language and heading."""
    english = split_sections(ENGLISH.read_text(encoding="utf-8"))
    expected = {section.key: section_hash(section) for section in english}
    english_text = ENGLISH.read_text(encoding="utf-8")
    english_blocks = fenced_blocks(english_text)
    english_spans = inline_code(english_text)
    problems: list[str] = []

    if current_language_line(english_text) != language_line("en"):
        problems.append("en: README.md's language links line does not match languages.json; run --update")

    for entry in languages():
        tag = entry["tag"]
        path = translation_path(tag)
        if not path.exists():
            problems.append(f"{tag}: {path.name} is listed in languages.json but does not exist")
            continue

        text = path.read_text(encoding="utf-8")
        bound = read_binding(text)
        if not bound:
            problems.append(f"{tag}: {path.name} carries no translation binding; run --update")
            continue

        for key, digest in expected.items():
            heading = _label(key)
            if key not in bound:
                problems.append(
                    f'{tag}: no binding for section "{heading}" - '
                    "the English file has a section this translation does not"
                )
            elif bound[key] != digest:
                problems.append(
                    f'{tag}: section "{heading}" is stale - the English text changed and {path.name} did not'
                )

        for key in bound.keys() - expected.keys():
            heading = _label(key)
            problems.append(f'{tag}: bound to section "{heading}", which the English file no longer has')

        if current_language_line(text) != language_line(tag):
            problems.append(f"{tag}: {path.name}'s language links line does not match languages.json; run --update")

        translated = split_sections(strip_binding(text))
        if len(translated) != len(english):
            problems.append(f"{tag}: {path.name} has {len(translated)} sections, English has {len(english)}")

        body = strip_binding(text)
        if fenced_blocks(body) != english_blocks:
            problems.append(
                f"{tag}: a fenced code block in {path.name} differs from the English one - "
                "code blocks are copied, not translated"
            )
        translated_spans = inline_code(body)
        if translated_spans != english_spans:
            missing = sorted(set(english_spans) - set(translated_spans))
            extra = sorted(set(translated_spans) - set(english_spans))
            detail = f" missing: {missing[:5]}" if missing else ""
            detail += f" unexpected: {extra[:5]}" if extra else ""
            problems.append(
                f"{tag}: the commands and paths in {path.name} are not the English set -"
                f"{detail or ' the counts differ'} - names are copied, not translated"
            )

    return problems


def update() -> list[str]:
    """Rewrite every translation's binding block. Returns what was written."""
    # Everything is computed before anything is written: a missing marker in
    # the third translation would otherwise leave the first two rewritten and
    # the repository half-updated, which is a worse state than not having run
    # the command at all.
    english_text = replace_language_line(ENGLISH.read_text(encoding="utf-8"), "en")
    block = render_binding(split_sections(english_text))

    pending: list[tuple[Path, str]] = [(ENGLISH, english_text)]
    for entry in languages():
        tag = entry["tag"]
        path = translation_path(tag)
        if not path.exists():
            continue
        body = strip_binding(path.read_text(encoding="utf-8"))
        pending.append((path, f"{block}\n\n{replace_language_line(body.lstrip(), tag)}"))

    for path, content in pending:
        path.write_text(content, encoding="utf-8")
    return [path.name for path, _ in pending[1:]]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--update", action="store_true", help="rebind every translation to the English README")
    args = parser.parse_args(argv)

    if args.update:
        written = update()
        print(f"bound {len(written)} translation(s): {', '.join(written) or '(none)'}")
        return 0

    problems = verify()
    if not problems:
        print(f"{len(languages())} translation(s) match README.md")
        return 0

    for problem in problems:
        print(f"error: {problem}", file=sys.stderr)
    print(
        "\nTranslate the sections named above, then rebind:\n"
        "  uv run python scripts/check_readme_translations.py --update",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
